-- generated by oracle2pg
create schema if not exists "FOX";

create table "FOX"."SS_CLS"
(
    "ID" serial primary key /* TODO or integer */,
    "CLS" varchar(100) not null,
    "QUERY" varchar(200) not null,
    "TABLE_NAME" varchar(30) not null
);

create table "FOX"."SUPPLIER"
(
    "SUPPLIER_ID" integer primary key,
    "SUPPLIER_NAME" varchar(50) not null,
    "CONTACT_NAME" varchar(50)
);

create table "FOX"."PRODUCTS"
(
    "PRODUCT_ID" integer not null,
    "SUPPLIER_ID" integer not null references "FOX"."SUPPLIER"
);
